### ISSUE TITLE
Could it be used in Windows or CentOS 5.X?

### ISSUE THREAD

**Issue by archonwang** [ascendro/redmine_issue_reminder#6]
Hi, ascendro

Could it be used in Windows or CentOS 5.X?
Thanks.

**Comment by MichaelKling** [comment]
Yes. The readme describes the setup on linux with a cronjob, but it should run anywhere where redmine is running and a periodical call to the rake task is defined.

To clear things up: 
The only OS dependency (beside the ones generated by redmine itself) is this cron job:

> 0 6 \* \* \* cd {REDMINE_ROOT} && rake reminder:exec RAILS_ENV="production" > /dev/null 2>&1

it defines that rake reminder:exec RAILS_ENV="production" is called every morning 6oclock (where it then sends all the reminder). 
In windows you can use the Windows Task Scheduler ( http://support.microsoft.com/kb/308569 ) for calling this rake task on a daily basis, in centos this seems to be the propper solution: http://www.centos.org/docs/5/html/Deployment_Guide-en-US/ch-autotasks.html

---

please tell me if this where the informations you searched so that i can close the issue

**Comment by archonwang** [comment]
Fine.  I'll try it in Windows.

Thanks.

**Comment by MichaelKling** [comment]
Ok, please post if it really working :)

**Comment by MichaelKling** [comment]
Steven Wong wrote:

> I tried it and it work well. The steps as follows:
> 
> Enviroment : Winxp + Redmine 1.2.X + Mysql 5.X
> 1. Write a bat file such as these
>    ########################################
> 
> echo on
> cd {REDMINE_ROOT}
> rake reminder:exec RAILS_ENV="production"
> 
> ########################################
> 1. config a schedule just follow this
>    http://www.iopus.com/guides/winscheduler.htm
> 2. then start the redmine server.
> 
> Thanks.
